name: memcached_client
version: 0.5.3
author: Henri Chen <henrichen@rikulo.org>
description: A Memcached client library written in Dart language.
homepage: https://github.com/rikulo/memcached-client
dependencies:
  crypto: ^2.0.0
  logging: ^0.11.3
dev_dependencies:
  test: ^0.12.0
environment:
  sdk: ">=1.4.0 <=2.0.0"
