name: memcached_client
version: 0.3.0+6
author: Henri Chen <henrichen@rikulo.org>
description: |
  A Memcached client library written in Dart language.
homepage: http://rikulo.org
dependencies:
  crypto: any
  logging: any
  unittest: any
